In [36]:
import preprocessor

print("Imported Successfully")

Imported Successfully

In [37]:
df = preprocessor.preprocess(data)
df.head()

,user_message,message_date,user,message
0,Messages and calls are end-to-end encrypted. O...,"1/28/25, 9:14 PM -",group_notification,Messages and calls are end-to-end encrypted. O...
1,"+91 99103 28501 created group ""CSE Internships...","1/28/25, 8:31 PM -",group_notification,"+91 99103 28501 created group ""CSE Internships..."
2,You joined using this group's invite link\n,"1/28/25, 9:14 PM -",group_notification,You joined using this group's invite link\n
3,+91 99957 42760 joined using a group link.\n,"1/28/25, 9:14 PM -",group_notification,+91 99957 42760 joined using a group link.\n
4,Ayush Ojha Nepal joined using a group link.\n,"1/28/25, 9:14 PM -",group_notification,Ayush Ojha Nepal joined using a group link.\n

In [38]:
import re
import pandas as pd

def preprocess(data):

    pattern = r'\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s'

    messages = re.split(pattern, data)[1:]
    dates = re.findall(pattern, data)

    df = pd.DataFrame({
        'user_message': messages,
        'message_date': dates
    })

    df['message_date'] = pd.to_datetime(
        df['message_date'],
        format='%m/%d/%y, %I:%M %p -'
    )

    users = []
    messages_list = []

    for message in df['user_message']:

        entry = re.split(r'([\w\W]+?):\s', message)

        if entry and len(entry) >= 3:
            users.append(entry[1])
            messages_list.append(entry[2])
        else:
            users.append('group_notification')
            messages_list.append(message)

    df['user'] = users
    df['message'] = messages_list

    df.drop(columns=['user_message'], inplace=True)

    return df

In [39]:
import importlib
import preprocessor

importlib.reload(preprocessor)

In [40]:
df = preprocessor.preprocess(data)

In [41]:
df.head()

,user_message,message_date,user,message
0,Messages and calls are end-to-end encrypted. O...,"1/28/25, 9:14 PM -",group_notification,Messages and calls are end-to-end encrypted. O...
1,"+91 99103 28501 created group ""CSE Internships...","1/28/25, 8:31 PM -",group_notification,"+91 99103 28501 created group ""CSE Internships..."
2,You joined using this group's invite link\n,"1/28/25, 9:14 PM -",group_notification,You joined using this group's invite link\n
3,+91 99957 42760 joined using a group link.\n,"1/28/25, 9:14 PM -",group_notification,+91 99957 42760 joined using a group link.\n
4,Ayush Ojha Nepal joined using a group link.\n,"1/28/25, 9:14 PM -",group_notification,Ayush Ojha Nepal joined using a group link.\n

In [42]:
print(df.columns)

Index(['user_message', 'message_date', 'user', 'message'], dtype='str')

In [43]:
import importlib
import helper

importlib.reload(helper)

In [44]:
num_messages, words, media, links = helper.fetch_stats('Overall', df)

print("Messages:", num_messages)
print("Words:", words)
print("Media:", media)
print("Links:", links)

Messages: 761
Words: 18562
Media: 105
Links: 225

In [45]:
dir(helper)

['URLExtract',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'extractor',
 'fetch_stats']

In [46]:
num_messages, words, media, links = helper.fetch_stats('Overall', df)

print("Messages:", num_messages)
print("Words:", words)
print("Media:", media)
print("Links:", links)

Messages: 761
Words: 18562
Media: 105
Links: 225

In [48]:
df.head()

,user_message,message_date,user,message
0,Messages and calls are end-to-end encrypted. O...,"1/28/25, 9:14 PM -",group_notification,Messages and calls are end-to-end encrypted. O...
1,"+91 99103 28501 created group ""CSE Internships...","1/28/25, 8:31 PM -",group_notification,"+91 99103 28501 created group ""CSE Internships..."
2,You joined using this group's invite link\n,"1/28/25, 9:14 PM -",group_notification,You joined using this group's invite link\n
3,+91 99957 42760 joined using a group link.\n,"1/28/25, 9:14 PM -",group_notification,+91 99957 42760 joined using a group link.\n
4,Ayush Ojha Nepal joined using a group link.\n,"1/28/25, 9:14 PM -",group_notification,Ayush Ojha Nepal joined using a group link.\n

In [58]:
print(df.dtypes)

user_message    str
message_date    str
user            str
message         str
dtype: object

In [61]:
import re

pattern = r'\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s'

dates = re.findall(pattern, data)

print(dates[:10])

['1/28/25, 9:14\u202fPM - ', '1/28/25, 8:31\u202fPM - ', '1/28/25, 9:14\u202fPM - ', '1/28/25, 9:14\u202fPM - ', '1/28/25, 9:14\u202fPM - ', '1/28/25, 9:14\u202fPM - ', '1/28/25, 9:15\u202fPM - ', '1/28/25, 9:15\u202fPM - ', '1/28/25, 9:15\u202fPM - ', '1/28/25, 9:16\u202fPM - ']

In [60]:
print(type(df['message_date'][0]))
print(df['message_date'][0])

<class 'str'>
1/28/25, 9:14 PM -

In [62]:
import re
import pandas as pd

def preprocess(data):

    pattern = r'\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s'

    messages = re.split(pattern, data)[1:]
    dates = re.findall(pattern, data)

    df = pd.DataFrame({
    'user_message': messages,
    'message_date': dates
   })

    # Fix WhatsApp special space character
    df['message_date'] = df['message_date'].str.replace('\u202f', ' ', regex=False)
    
    # Convert string to datetime
    df['message_date'] = pd.to_datetime(
        df['message_date'],
        format='%m/%d/%y, %I:%M %p - '
    )
    
    users = []
    messages_list = []

    for message in df['user_message']:

        entry = re.split(r'([\w\W]+?):\s', message)

        if len(entry) >= 3:
            users.append(entry[1])
            messages_list.append(entry[2])
        else:
            users.append('group_notification')
            messages_list.append(message)

    df['user'] = users
    df['message'] = messages_list
    df['year'] = df['message_date'].dt.year
    df['month_num'] = df['message_date'].dt.month
    df['month'] = df['message_date'].dt.month_name()
    df['day'] = df['message_date'].dt.day

    return df

In [63]:
import importlib
import preprocessor

importlib.reload(preprocessor)

df = preprocessor.preprocess(data)

print(df.dtypes)

user_message               str
message_date    datetime64[us]
user                       str
message                    str
year                     int32
month_num                int32
month                      str
day                      int32
dtype: object

In [64]:
import importlib
import helper

importlib.reload(helper)

timeline = helper.monthly_timeline('Overall', df)

timeline.head()

   year  month_num     month  message           time
0  2025          1   January       79   January-2025
1  2025          2  February        4  February-2025
2  2025          3     March       19     March-2025
3  2025          4     April        5     April-2025
4  2025          5       May       20       May-2025

In [67]:
import importlib
import helper

importlib.reload(helper)

timeline = helper.monthly_timeline('Overall', df)
print(timeline.head())

daily = helper.daily_timeline('Overall', df)
print(daily.head())

   year  month_num     month  message           time
0  2025          1   January       79   January-2025
1  2025          2  February        4  February-2025
2  2025          3     March       19     March-2025
3  2025          4     April        5     April-2025
4  2025          5       May       20       May-2025
         message_date  message
0 2025-01-28 20:31:00        1
1 2025-01-28 21:14:00        5
2 2025-01-28 21:15:00        3
3 2025-01-28 21:16:00        3
4 2025-01-28 21:18:00        2

In [75]:
import importlib
import preprocessor

importlib.reload(preprocessor)

df = preprocessor.preprocess(data)

In [76]:
print(df.columns)

Index(['user_message', 'message_date', 'user', 'message', 'year', 'month_num',
       'month', 'day'],
      dtype='str')

In [78]:
import importlib
import helper

importlib.reload(helper)

daily = helper.daily_timeline('Overall', df)

daily.head()

  message_date  message
0   2025-01-28       60
1   2025-01-29       16
2   2025-01-31        3
3   2025-02-01        1
4   2025-02-14        3

In [79]:
import importlib
import helper

importlib.reload(helper)

x, new_df = helper.most_busy_users(df)

print(x)
new_df.head()

user
+91 89173 80884        267
+91 79780 42894        170
group_notification     121
+91 98612 44755         86
Ankit Singha CSE PC     40
Name: count, dtype: int64

                  name  percent
0      +91 89173 80884    35.09
1      +91 79780 42894    22.34
2   group_notification    15.90
3      +91 98612 44755    11.30
4  Ankit Singha CSE PC     5.26

In [3]:
import importlib
import helper

importlib.reload(helper)

In [6]:
import os

print(os.listdir('data'))

['.ipynb_checkpoints', 'WhatsApp Chat with CSE Placements 2027(B.Tech.).txt', 'WhatsApp Chat with Divyanshu Sah.txt']

In [7]:
with open(
    'data/WhatsApp Chat with CSE Placements 2027(B.Tech.).txt',
    'r',
    encoding='utf-8'
) as f:
    data = f.read()

In [8]:
import importlib
import preprocessor

importlib.reload(preprocessor)

df = preprocessor.preprocess(data)

print(df.columns)

Index(['user_message', 'message_date', 'user', 'message', 'year', 'month_num',
       'month', 'day', 'day_name', 'hour', 'period'],
      dtype='str')

In [9]:
import importlib
import helper

importlib.reload(helper)

user_heatmap = helper.activity_heatmap('Overall', df)

user_heatmap.head()

period,00-1,1-2,10-11,11-12,12-13,13-14,14-15,15-16,16-17,17-18,...,2-3,20-21,21-22,22-23,23-00,3-4,6-7,7-8,8-9,9-10
day_name,,,,,,,,,,,,,,,,,,,,,
Friday,6.0,2.0,6.0,7.0,6.0,6.0,10.0,8.0,8.0,6.0,...,1.0,6.0,6.0,11.0,5.0,0.0,0.0,0.0,4.0,4.0
Monday,3.0,0.0,8.0,6.0,8.0,4.0,7.0,11.0,6.0,7.0,...,0.0,7.0,4.0,18.0,1.0,0.0,0.0,0.0,4.0,7.0
Saturday,12.0,1.0,3.0,1.0,7.0,10.0,4.0,3.0,0.0,5.0,...,0.0,3.0,6.0,2.0,8.0,2.0,0.0,0.0,2.0,0.0
Sunday,1.0,0.0,2.0,2.0,4.0,5.0,4.0,3.0,2.0,0.0,...,0.0,1.0,4.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0
Thursday,5.0,1.0,9.0,3.0,7.0,7.0,7.0,10.0,4.0,5.0,...,0.0,4.0,3.0,4.0,2.0,0.0,3.0,3.0,1.0,5.0

In [10]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\sunny\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.6)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sunny\appdata\roaming\python\python313\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\sunny\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
helper.fetch_stats('Overall', df)

helper.monthly_timeline('Overall', df)

helper.daily_timeline('Overall', df)

helper.most_busy_users(df)

helper.activity_heatmap('Overall', df)

period,00-1,1-2,10-11,11-12,12-13,13-14,14-15,15-16,16-17,17-18,...,2-3,20-21,21-22,22-23,23-00,3-4,6-7,7-8,8-9,9-10
day_name,,,,,,,,,,,,,,,,,,,,,
Friday,6.0,2.0,6.0,7.0,6.0,6.0,10.0,8.0,8.0,6.0,...,1.0,6.0,6.0,11.0,5.0,0.0,0.0,0.0,4.0,4.0
Monday,3.0,0.0,8.0,6.0,8.0,4.0,7.0,11.0,6.0,7.0,...,0.0,7.0,4.0,18.0,1.0,0.0,0.0,0.0,4.0,7.0
Saturday,12.0,1.0,3.0,1.0,7.0,10.0,4.0,3.0,0.0,5.0,...,0.0,3.0,6.0,2.0,8.0,2.0,0.0,0.0,2.0,0.0
Sunday,1.0,0.0,2.0,2.0,4.0,5.0,4.0,3.0,2.0,0.0,...,0.0,1.0,4.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0
Thursday,5.0,1.0,9.0,3.0,7.0,7.0,7.0,10.0,4.0,5.0,...,0.0,4.0,3.0,4.0,2.0,0.0,3.0,3.0,1.0,5.0
Tuesday,4.0,0.0,1.0,10.0,3.0,8.0,5.0,8.0,10.0,8.0,...,0.0,5.0,56.0,13.0,8.0,0.0,0.0,1.0,1.0,5.0
Wednesday,8.0,1.0,0.0,5.0,10.0,12.0,6.0,9.0,16.0,4.0,...,1.0,16.0,3.0,9.0,15.0,0.0,0.0,0.0,3.0,1.0

In [13]:
import importlib
import helper

importlib.reload(helper)

wc = helper.create_wordcloud('Overall', df)

In [14]:
import importlib
import helper

importlib.reload(helper)

print(dir(helper))

['URLExtract', 'WordCloud', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'activity_heatmap', 'create_wordcloud', 'daily_timeline', 'extractor', 'fetch_stats', 'monthly_timeline', 'most_busy_users']

In [16]:
wc = helper.create_wordcloud('Overall', df)

type(wc)

wordcloud.wordcloud.WordCloud

In [17]:
import importlib
import helper

importlib.reload(helper)

common_df = helper.most_common_words(
    'Overall',
    df
)

common_df.head()

           0    1
0          |  383
1          *  231
2  *eligible  208
3          -  205
4        all  179

In [19]:
!pip install emoji

Collecting emoji
  Using cached emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Using cached emoji-2.15.0-py3-none-any.whl (608 kB)
Installing collected packages: emoji
Successfully installed emoji-2.15.0

[notice] A new release of pip is available: 25.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import importlib
import helper

importlib.reload(helper)

emoji_df = helper.emoji_helper('Overall', df)

emoji_df.head()

   0   1
0  🎉  40
1  🥳  18
2  ✨  10
3  🎊   3
4  👍   1

In [23]:
import importlib
import helper

importlib.reload(helper)

print(dir(helper))

['Counter', 'URLExtract', 'WordCloud', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'activity_heatmap', 'create_wordcloud', 'daily_timeline', 'emoji', 'emoji_helper', 'extractor', 'fetch_stats', 'monthly_activity_map', 'monthly_timeline', 'most_busy_users', 'most_common_words', 'pd']

In [24]:
helper.monthly_activity_map('Overall', df)

    year  month_num      month  message
0   2025          1    January       79
1   2025          2   February        4
2   2025          3      March       19
3   2025          4      April        5
4   2025          5        May       20
5   2025          6       June       22
6   2025          7       July       81
7   2025          8     August       79
8   2025          9  September       62
9   2025         10    October       41
10  2025         11   November       15
11  2025         12   December       45
12  2026          1    January       60
13  2026          2   February       30
14  2026          3      March       45
15  2026          4      April       50
16  2026          5        May       68
17  2026          6       June       36